config/routes.rb
Rails.application.routes.draw do
  root 'posts#new'

  get    '/signup',    to:  'users#new'
  post   '/signup',    to:  'users#create'
  get    '/login',     to:  'sessions#new'
  post   '/login',     to:  'sessions#create'
  delete '/logout',    to:  'sessions#destroy'

  resources :users,    only: [:new, :create]
  resources :posts,    only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :content, presence: true, length: { maximum: 140 }
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts, dependent: :destroy
	before_save { email.downcase! }

	validates :name,  presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
	
	def require_login
		flash.now[:alert] = "vous devez etre connecte pour voir cette page!"
		redirect_to posts_path if current_user.nil?
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def new
  	@post = Post.new
  end

  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		flash[:success] = "poste cree avec succes!"
  		redirect_to posts_path
  	else
  		render :new
  	end
  end

  def index
  	@posts = Post.all
  end

  private
  	def post_params
  		params.require(:post).permit(:content) 
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by(email: params[:session][:email.downcase])

		if @user&.authenticate(params[:session][:password])
			log_in @user
			redirect_to posts_path
		else
			flash.now[:danger] = "mot de passe ou e-mail invalide"
			render :new
		end
	end

	def destroy
		session.delete(:user_id) if logged_in?
		redirect_to posts_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "felicitations #{@user.name}, tu existes"
  		redirect_to posts_path
  	else
  		render :new
  	end
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email,
  									 :password,
  									 :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		end
	end

	

	def log_in(user)
		session[:user_id] = user.id
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
	<div>
		Le formulaire contient <%= pluralize(object.errors.count, "erreur") %>
	</div>
	<ul>
		<% object.errors.full_messages.each do |err| %>
			<li><%= err %></li>
		<% end %>
	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |msg_type, msg| %>
      <%= content_tag(:div, msg) %>
    <% end %>
    <% if current_user %>
      <h4><%= current_user.name %> est connectee</h4>
      <%= link_to "Se Deconnecter", logout_path, method: :delete %>
      <%= link_to "Creer un article", new_post_path %>
    <% else %>
      <%= link_to "S'Identifier", login_path %>
      <%= link_to "Creer un compte", signup_path %>
    <% end %>
    <%= link_to "Tous les articles", posts_path %>
    
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Tous les articles</h1>

<% if !@posts.empty? %>
	<ul>
		<% @posts.each do |p| %>
		  <li>
		  	<%= p.content %>
		  	<% if logged_in? %>
		  	  <i><%= p.user.name %></i>
		  	<% else %>
		  	  <i>un secret</i>
		  	<% end %>
		  </li>

		<% end %>
	</ul>
<% else %>
	<p>rien :(</p>
<% end %>

app/views/posts/new.html.erb
<h1>Creer un article</h1>

<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.submit "creer" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>S'Inscrire</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "S'Inscire" %>
<% end %>